source 'https://github.com/CocoaPods/Specs.git'
# 使用frameworks
use_frameworks!
# 忽略pod里面警告
inhibit_all_warnings!
# 支持的平台
platform :ios, '14.0'


##################
#      PODS      #
##################

# === 私有组件 === #
def pods_private
  # 本地路径
  $root = '../../../'
  $business = 'Business/'
  $ui = 'UI/'
  $basic = 'Basic/'
  $server = 'Server/'
  
  # Business
  pod 'SFUser',         :path => $root + $business + 'SFUser/'
  
  # UI
  pod 'SFUI',           :path => $root + $ui + 'SFUI/'
  
  # Basic
  pod 'SFBase',         :path => $root + $basic + 'SFBase/'
  pod 'SFExtension',    :path => $root + $basic + 'SFExtension/'
    
  # Server
  pod 'SFLogger',       :path => $root + $server + 'SFLogger/'
 
 
end

# === 第三方组件 === #
def pods_third
  
  pod 'R.swift'
  
end


##################
#     TARGET     #
##################

# === SFUser_Example === #
target 'SFUser_Example' do
  
  pods_private
  pods_third
  
end


#===================#
#=      COLOR      =#
#===================#
# 颜色定义
COLOR_RED = "\033[0;31m"
COLOR_GREEN = "\033[0;32m"
COLOR_YELLOW = "\033[0;33m"
COLOR_BLUE = "\033[0;34m"
COLOR_PURPLE = "\033[0;35m"
COLOR_CYAN = "\033[0;36m"
COLOR_RESET = "\033[0m"

# 彩色打印方法
def colorize(color, text)
  puts "#{color}#{text}#{COLOR_RESET}"
end



#===================#
#=   POD INSTALL   =#
#===================#
# pre_install
pre_install do |installer|
  colorize(COLOR_BLUE, ">>>>>>>>>>> pre_install [开始] <<<<<<<<<<<<")
  
  colorize(COLOR_GREEN, ">>>>>>>>>>> pre_install [结束] <<<<<<<<<<<<")
end

# post_install
post_install do |installer|
  colorize(COLOR_BLUE, ">>>>>>>>>>> post_install [开始] <<<<<<<<<<<<")
  
  colorize(COLOR_GREEN, ">>>>>>>>>>> post_install [结束] <<<<<<<<<<<<")
end
