//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

private class BundleFinder {}
let R = _R(bundle: Bundle(for: BundleFinder.self))

struct _R {
  let bundle: Foundation.Bundle
  var image: image { .init(bundle: bundle) }
  var file: file { .init(bundle: bundle) }
  var nib: nib { .init(bundle: bundle) }
  var storyboard: storyboard { .init(bundle: bundle) }

  func image(bundle: Foundation.Bundle) -> image {
    .init(bundle: bundle)
  }
  func file(bundle: Foundation.Bundle) -> file {
    .init(bundle: bundle)
  }
  func nib(bundle: Foundation.Bundle) -> nib {
    .init(bundle: bundle)
  }
  func storyboard(bundle: Foundation.Bundle) -> storyboard {
    .init(bundle: bundle)
  }
  func validate() throws {
    try self.nib.validate()
    try self.storyboard.validate()
  }

  struct project {
    let developmentRegion = "English"
  }

  /// This `_R.image` struct is generated, and contains static references to 1 images, and 3 namespaces.
  struct image {
    let bundle: Foundation.Bundle

    /// Image `user`.
    var user: RswiftResources.ImageResource { .init(name: "user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    var gender: gender { .init(bundle: bundle) }
    var info: info { .init(bundle: bundle) }
    var sign: sign { .init(bundle: bundle) }

    func gender(bundle: Foundation.Bundle) -> gender {
      .init(bundle: bundle)
    }
    func info(bundle: Foundation.Bundle) -> info {
      .init(bundle: bundle)
    }
    func sign(bundle: Foundation.Bundle) -> sign {
      .init(bundle: bundle)
    }


    /// This `_R.image.gender` struct is generated, and contains static references to 2 genders.
    struct gender {
      let bundle: Foundation.Bundle

      /// Image `gender/female`.
      var female: RswiftResources.ImageResource { .init(name: "gender/female", path: ["gender"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `gender/male`.
      var male: RswiftResources.ImageResource { .init(name: "gender/male", path: ["gender"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }

    /// This `_R.image.info` struct is generated, and contains static references to 9 infos.
    struct info {
      let bundle: Foundation.Bundle

      /// Image `info/account`.
      var account: RswiftResources.ImageResource { .init(name: "info/account", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/address`.
      var address: RswiftResources.ImageResource { .init(name: "info/address", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/avatar`.
      var avatar: RswiftResources.ImageResource { .init(name: "info/avatar", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/birthday`.
      var birthday: RswiftResources.ImageResource { .init(name: "info/birthday", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/email`.
      var email: RswiftResources.ImageResource { .init(name: "info/email", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/gender`.
      var gender: RswiftResources.ImageResource { .init(name: "info/gender", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/motto`.
      var motto: RswiftResources.ImageResource { .init(name: "info/motto", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/nickname`.
      var nickname: RswiftResources.ImageResource { .init(name: "info/nickname", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `info/phone`.
      var phone: RswiftResources.ImageResource { .init(name: "info/phone", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
    }

    /// This `_R.image.sign` struct is generated, and contains static references to 3 signs, and 1 namespaces.
    struct sign {
      let bundle: Foundation.Bundle

      /// Image `sign/account`.
      var account: RswiftResources.ImageResource { .init(name: "sign/account", path: ["sign"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `sign/code`.
      var code: RswiftResources.ImageResource { .init(name: "sign/code", path: ["sign"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

      /// Image `sign/pwd`.
      var pwd: RswiftResources.ImageResource { .init(name: "sign/pwd", path: ["sign"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      var eye: eye { .init(bundle: bundle) }

      func eye(bundle: Foundation.Bundle) -> eye {
        .init(bundle: bundle)
      }


      /// This `_R.image.sign.eye` struct is generated, and contains static references to 2 eyes.
      struct eye {
        let bundle: Foundation.Bundle

        /// Image `sign/eye/close`.
        var close: RswiftResources.ImageResource { .init(name: "sign/eye/close", path: ["sign", "eye"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }

        /// Image `sign/eye/open`.
        var `open`: RswiftResources.ImageResource { .init(name: "sign/eye/open", path: ["sign", "eye"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
      }
    }
  }

  /// This `_R.file` struct is generated, and contains static references to 1 resource files.
  struct file {
    let bundle: Foundation.Bundle

    /// Resource file `Localizable.xcstrings`.
    var localizableXcstrings: RswiftResources.FileResource { .init(name: "Localizable", pathExtension: "xcstrings", bundle: bundle, locale: LocaleReference.none) }
  }

  /// This `_R.nib` struct is generated, and contains static references to 1 nibs.
  struct nib {
    let bundle: Foundation.Bundle

    /// Nib `LaunchScreen`.
    var launchScreen: RswiftResources.NibReference<UIKit.UIView> { .init(name: "LaunchScreen", bundle: bundle) }

    func validate() throws {

    }
  }

  /// This `_R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    let bundle: Foundation.Bundle
    var main: main { .init(bundle: bundle) }

    func main(bundle: Foundation.Bundle) -> main {
      .init(bundle: bundle)
    }
    func validate() throws {
      try self.main.validate()
    }


    /// Storyboard `Main`.
    struct main: RswiftResources.StoryboardReference, RswiftResources.InitialControllerContainer {
      typealias InitialController = ViewController

      let bundle: Foundation.Bundle

      let name = "Main"
      func validate() throws {

      }
    }
  }
}