//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import RswiftResources
import UIKit

public let R = Resource()

public struct Resource {
    
    public static var imageBundle: Foundation.Bundle = SFLibUser.bundle ?? .main
    public static var fileBundle: Foundation.Bundle = SFLibUser.bundle ?? .main
    
    public var image: image { .init(bundle: Self.imageBundle) }
    public var file: file { .init(bundle: Self.fileBundle) }
        
    
    /// This `_R.image` struct is generated, and contains static references to 1 images, and 3 namespaces.
    public struct image {
        public let bundle: Foundation.Bundle
        
        /// Image `user`.
        public var user: RswiftResources.ImageResource { .init(name: "user", path: [], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        public var gender: gender { .init(bundle: bundle) }
        public var info: info { .init(bundle: bundle) }
        public var sign: sign { .init(bundle: bundle) }
        
        public func gender(bundle: Foundation.Bundle) -> gender {
            .init(bundle: bundle)
        }
        public func info(bundle: Foundation.Bundle) -> info {
            .init(bundle: bundle)
        }
        public func sign(bundle: Foundation.Bundle) -> sign {
            .init(bundle: bundle)
        }
        
        
        /// This `_R.image.gender` struct is generated, and contains static references to 2 genders.
        public struct gender {
            public let bundle: Foundation.Bundle
            
            /// Image `gender/female`.
            public var female: RswiftResources.ImageResource { .init(name: "gender/female", path: ["gender"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `gender/male`.
            public var male: RswiftResources.ImageResource { .init(name: "gender/male", path: ["gender"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
        
        /// This `_R.image.info` struct is generated, and contains static references to 9 infos.
        public struct info {
            public let bundle: Foundation.Bundle
            
            /// Image `info/account`.
            public var account: RswiftResources.ImageResource { .init(name: "info/account", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/address`.
            public var address: RswiftResources.ImageResource { .init(name: "info/address", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/avatar`.
            public var avatar: RswiftResources.ImageResource { .init(name: "info/avatar", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/birthday`.
            public var birthday: RswiftResources.ImageResource { .init(name: "info/birthday", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/email`.
            public var email: RswiftResources.ImageResource { .init(name: "info/email", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/gender`.
            public var gender: RswiftResources.ImageResource { .init(name: "info/gender", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/motto`.
            public var motto: RswiftResources.ImageResource { .init(name: "info/motto", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/nickname`.
            public var nickname: RswiftResources.ImageResource { .init(name: "info/nickname", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `info/phone`.
            public var phone: RswiftResources.ImageResource { .init(name: "info/phone", path: ["info"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
        }
        
        /// This `_R.image.sign` struct is generated, and contains static references to 3 signs, and 1 namespaces.
        public struct sign {
            public let bundle: Foundation.Bundle
            
            /// Image `sign/account`.
            public var account: RswiftResources.ImageResource { .init(name: "sign/account", path: ["sign"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `sign/code`.
            public var code: RswiftResources.ImageResource { .init(name: "sign/code", path: ["sign"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            
            /// Image `sign/pwd`.
            public var pwd: RswiftResources.ImageResource { .init(name: "sign/pwd", path: ["sign"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            public var eye: eye { .init(bundle: bundle) }
            
            public func eye(bundle: Foundation.Bundle) -> eye {
                .init(bundle: bundle)
            }
            
            
            /// This `_R.image.sign.eye` struct is generated, and contains static references to 2 eyes.
            public struct eye {
                public let bundle: Foundation.Bundle
                
                /// Image `sign/eye/close`.
                public var close: RswiftResources.ImageResource { .init(name: "sign/eye/close", path: ["sign", "eye"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
                
                /// Image `sign/eye/open`.
                public var `open`: RswiftResources.ImageResource { .init(name: "sign/eye/open", path: ["sign", "eye"], bundle: bundle, locale: nil, onDemandResourceTags: nil) }
            }
        }
    }
    
    /// This `_R.file` struct is generated, and contains static references to 1 resource files.
    public struct file {
        public let bundle: Foundation.Bundle
        
        /// Resource file `Localizable.xcstrings`.
        public var localizableXcstrings: RswiftResources.FileResource { .init(name: "Localizable", pathExtension: "xcstrings", bundle: bundle, locale: LocaleReference.none) }
    }    
    
}
